spring:
  application:
    name: CurrencyExchangeRateApi
  cache:
    type: simple
    cache-names: currencyRates
  datasource:
    url: jdbc:h2:mem:security
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

currency-api:
  url: "https://www.cbr.ru/scripts/XML_daily.asp"

resilience4j:
  circuitbreaker:
    instances:
      currencyService:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true