spring:
  application:
    name: CustomKudaGoAPI
  liquibase:
    change-log: classpath:db/changelog/db.changelog-1.0.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect