name: CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}v2
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check gradle wrapper files
        run: ls gradle/wrapper

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: CustomKudaGoAPI

      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport
        working-directory: CustomKudaGoAPI

      - name: Run static analysis (e.g., Checkstyle)
        run: ./gradlew check
        working-directory: CustomKudaGoAPI

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:latest .
          docker push ghcr.io/${{ github.repository }}/my-app:latest
